openapi: 3.0.0
servers:
  - url: 'https://api.avito.ru/'
info:
  version: '1'
  title: Авито API для бизнеса
  description: >
    # Общая информация

    Описание API произведено в формате [**Swagger
    3.0**](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md).

    Вы можете использовать данный файл для ознакомления с методами API, а также
    для генерации базового

    кода для работы с API на удобном для вас языке программирования с помощью
    утилиты

    [**Swagger Codegen**](https://swagger.io/swagger-codegen/) или online
    сервиса [**Swagger Editor**](https://editor.swagger.io/).


    **Авито API для бизнеса предоставляется согласно [Условиям
    использования](https://api.avito.ru/docs/public/APITermsOfServiceV1.pdf).**


    По всем вопросам работы с API необходимо обращаться в Службу Поддержки
    профессиональных инструментов:


    <li>телефон: <b>+7 495 777-10-66</b></li>

    <li>email: <a
    href="mailto:supportautoload@avito.ru">supportautoload@avito.ru</a></li>


    # Типы авторизации

    Для использования данного API запрос должен быть авторизован. В данный
    момент API Авито использует следующие механизмы авторизации.


    <!-- ReDoc-Inject: <security-definitions> -->


    Подробнее о каждом механизме и его назначении можно прочитать в
    соответствующем разделе.
  contact:
    email: supportautoload@avito.ru
tags:
  - name: Access
    x-displayName: Персональная авторизация
    description: >
      Для работы с API от своего лица необходимо получить токен авторизации —
      отдельный для каждой учетной записи на Авито.

        1. Получаем **client_id** и **client_secret** в Службе Поддержки
        2. Выписываем себе токен:
           ```
           curl -i 'https://api.avito.ru/token/?grant_type=client_credentials&client_id=<CLIENT_ID>&client_secret=<CLIENT_SECRET>'
           ```
        3. Далее выполняем запросы к API с заголовком `Authorization: Bearer <ACCESS_TOKEN>`

        Время действия токена ограничено - 1 час с момента его получения.
        После этого вам необходимо получить новый токен.
  - name: ApplicationAccess
    x-displayName: Авторизация для приложений
    description: >
      Для работы с API приложений от лица пользователя есть возможность получить
      токен через Authorization Code механизм протокола OAuth2. Для этого в
      первую очередь нужно зарегистрировать приложение через службу поддержки.
      После успешной регистрации ваше приложение получит возможность работать с
      API Авито от лица пользователя (если последний выдаст на это разрешение).


      Подробнее об Authorization Code флоу протокола OAuth2 можно почитать [в
      статье](https://www.digitalocean.com/community/tutorials/oauth-2-ru).
      Процесс работы с этим флоу в API Авито отличается только незначительными
      деталями – ниже по шагам описан процесс интеграции.


      Обратите внимание, что не все доступные API сейчас работают через механизм
      авторизации для приложений (в данный момент только API мессенджера Авито
      поддерживает этот механизм).


      ### Шаг 1: Регистрация приложения


      Регистрируем приложение через Службу Поддержки. Для регистрации нужно
      указать:


      * Имя приложения, которое будет выводиться пользователям в форме
      подтверждения прав

      * ID пользователя Авито, которому будут принадлежать права на
      зарегистрированное приложение

      * Redirect URI - адрес, на который сайт Авито средиректит пользователя
      после подтверждения прав

      * Скоупы, которые необходимы вашему приложению (подробнее о доступных
      скоупах ниже)

      * Описание приложения - для каких целей вы планируете использовать доступ
      к данным


      В данный момент мы регистрируем только доверенные приложения от наших
      партнеров.


      Скоупы определяют права, на которые ваше приложение сможет рассчитывать
      после подверждения авторизации пользователем. Доступные скоупы перечислены
      [тут](#section/Tipy-avtorizacii/Authorization%20Code).


      ### Шаг 2: Ссылка с кодом авторизации


      Сначала пользователю предоставляется ссылка следующего вида:


      ```

      https://avito.ru/oauth?response_type=code&client_id=<CLIENT_ID>&scope=messenger:read,messenger:write

      ```


      ### Шаг 3: Пользователь авторизует приложение


      Пользователь переходит по ссылке на Авито, аутентифицируется при
      необходимости, затем подтверждает выдачу необходимых прав вашему
      приложению.


      ### Шаг 4: Приложение получает код авторизации


      Если пользователь выбирает "Авторизовать приложение", Авито перенаправляет
      пользовательский агент (браузер) по URI перенаправления (Redirect URI),
      который был задан на этапе регистрации приложения и добавляет в него
      параметр `code`. Например, если при регистрации в качестве Redirect URI
      был указан адрес `https://example.com/callback/avito`, то мы перенаправим
      пользователя на:


      ```

      https://example.com/callback/avito?code=<AUTHORIZATION_CODE>

      ```


      ### Шаг 5: Приложение запрашивает токен доступа


      Приложение запрашивает токен доступа у API Авито путём отправки
      авторизационного кода и аутентификационной информации (включая секрет
      приложения). Ниже представлен пример GET-запроса для получения access
      token:


      ```

      https://api.avito.ru/token/?grant_type=authorization_code&client_id=<CLIENT_ID>&client_secret=<CLIENT_SECRET>&code=<AUTHORIZATION_CODE>

      ```


      ### Шаг 6: Приложение получает токен доступа


      Если авторизация прошла успешно, API возвращает токен доступа (а также
      токен для обновления токена доступа - refresh token). Весь ответ сервера
      может выглядеть следующим образом:


      ```

      {
          "access_token": "<ACCESS_TOKEN>",
          "expires_in": 3600,
          "refresh_token": "<REFRESH_TOKEN>",
          "scope": "messenger:read,messenger:write",
          "token_type": "Bearer"
      }

      ```


      Приложение сохраняет access_token и refresh_token.


      ### Шаг 7: Приложение делает запросы к API c токеном доступа


      Далее приложение может выполнять запросы к API с заголовком
      `Authorization: Bearer <ACCESS_TOKEN>`


      ### Шаг 8: Приложение обновляет access_token


      Время действия access token ограничено - 1 час с момента его получения.
      После этого вам необходимо получить новый токен.


      После истечения срока действия токена доступа все запросы к API с его
      использованием будут возвращать код ошибки 403. Сохраненный refresh token
      может быть использован для получения нового токена доступа от
      авторизационного сервера.


      Ниже представлен пример GET-запроса, использующего refresh token для
      обновления токена доступа:


      ```

      https://api.avito.ru/token/?grant_type=refresh_token&client_id=<CLIENT_ID>&client_secret=<CLIENT_SECRET>&refresh_token=<REFRESH_TOKEN>

      ```


      В ответ приложение получит точно такой же JSON, как и при обмене code на
      access token. При этом будет получен не только новый access_token, но и
      новый refresh_token. Обновите оба значения в своей базе данных.


      ### Дополнительный параметр state


      Для того чтобы защитить данные пользователей мы крайне рекомендуем
      использовать параметр state. Этот параметр позволяет защититься от
      CSRF-атак и восстановить состояние вашего приложения на момент начала
      авторизации. Подробнее, зачем нужен параметр state, можно прочитать
      [тут](https://auth0.com/docs/protocols/oauth2/oauth-state).


      Для того, чтобы использовать state – просто включите его в начальный URL:


      ```

      https://avito.ru/oauth?response_type=code&client_id=<CLIENT_ID>&scope=messenger:read,messenger:write&state=<STATE>

      ```


      В итоге state будет содержаться в финальном Redirect URI, на который Авито
      перенаправляет пользователя после подтверждения прав доступа. Например,
      если при регистрации в качестве Redirect URI был указан адрес
      `https://example.com/callback/avito`, то мы перенаправим пользователя на:


      ```

      https://example.com/callback/avito?code=<AUTHORIZATION_CODE>&state=<STATE>

      ```


      Не передавайте чувствительные данные в открытом виде в этом параметре.
      Генерируйте уникальное временное значение state в вашем приложении.
  - name: User
    x-displayName: Пользователь
    description: Методы API для получения информации о пользователе Авито
  - name: Autoload
    x-displayName: Сервис Автозагрузка
    description: Методы API для получения информации об автозагрузке объявлений
  - name: Item
    x-displayName: Объявления
    description: Общие методы API для работы с объявлениями на Авито
  - name: Autoteka
    x-displayName: Автотека
    description: >
      Методы API для работы с сервисом Автотека.


      Для того чтобы воспользоваться данным функционалом Вам необходимо стать
      партнером Автотеки.


      Стать официальным партнером и получить доступ к данным методам можно,

      подав заявку через [**Обратную связь с
      Autoteka**](https://autoteka.ru/feedback).


      В качестве темы запроса нужно указать **"Сотрудничество"**.



      **Алгоритм получения отчёта**

        1. Отправляем [запрос на создание превью по VIN](#operation/postPreviewByVin) или [запрос на создание превью по государственному номеру](#operation/postPreviewByRegNumber)
        2. Отправляем [запрос на получение превью по ID](#operation/getPreview)
        3. Проверяем статус:
            - Если `processing`, то повторяем шаг 2
            - Если `notFound`, то это значит, что по данному VIN нельзя сформировать отчёт
            - Если `success`, то отправляем [запрос на создание отчёта по превью](#operation/postReport)
  - name: Realty
    x-displayName: Краткосрочная аренда
    description: Методы API для партнёров для работы с API краткосрочной аренды (STR)
  - name: Job
    x-displayName: Работа
    description: |
      Методы API для работы с функциональностью вертикали Авито Работа.
  - name: Messenger
    x-displayName: Мессенджер
    description: >
      Методы API для работы с Мессенджером.


      ## Работа с API мессенджера


      API мессенджера предоставляет набор методов, необходимых для получения
      списка чатов пользователя на Авито, получения сообщений в чате, отправки
      сообщения в чат и другие. Благодаря этому API можно организовать
      интеграцию между мессенджером Авито и сторонней системой в обе стороны.


      **Важно!** API мессенджера Авито позволяет получить список сообщений в
      чате. **Не используйте данный метод для поллинга новых сообщений** на
      активном экране пользователя. Используйте только для изначальной отрисовки
      сообщений. Для получения обновлений в реальном времени используйте
      механизм webhooks (см. ниже). При активном поллинге со стороны клиентов
      API будет возвращать ошибку HTTP 429. Мы также можем полностью
      заблокировать ваш клиент в случае если он создает большую нагрузку на API.


      ## Уведомления


      **Уведомления** – HTTP POST запрос от Авито к вашему сайту или приложению,
      также их называют **webhooks**.

      Body запроса представляет собой JSON.



      Уведомления имеют версионирование. Подписаться на нужную версию
      уведомлений можно отправив запрос на соответствующую ручку:

      * messenger/v2/webhook - 2-я версия

      * messenger/v1/webhook - 1-я версия (**DEPRECATED**, используйте v2)


      Несколько важных моментов при работе с уведомлениями:

      * При получении вебхука ваш сервер должен обязательно вернуть HTTP status
      code 200

      * В случае сетевых ошибок, таймаутов и ответов с HTTP статус кодом >= 500
      мы пытаемся переотправить вебхук (несколько раз в течение нескольких
      секунд)

      * Если уведомление по пользователю длительное время отдает отличный от 200
      HTTP статус код – подписка пользователя будет автоматически удалена


      ### Уведомления V2

      HTTP запрос к вашей системе будет содержать следующий payload:

      ```

      {
        "id": "3cc1cbe7-6477-4aad-9272-952f8afb3c30",
        "version": "v2.0.0",
        "timestamp": 1587562733,
        "payload": {
          "type": "message",
          "value": {
            "id": "256347f56e4819deb6f8c59ff14d62a8",
            "type": "text",
            "chat_id": "u2i-1123-1123",
            "user_id": 94235311,
            "author_id": 78743309,
            "created": 1566290351,
            "content": {
              "text": "привет"
            }
          }
        }
      }

      ```


      Payload состоит из полей:

      * type – тип нотификации. На данный момент поддерживается только
      **message**. В будущем в рамках уведомлений v2 могут начать приходить
      новые типы нотификаций помимо **message**. Ваше приложение должно
      игнорировать неизвестные ему типы.

      * value – поля нотификации. В зависимости от типа нотификации, value будет
      иметь разные поля. **Необходимо** обрабатывать неизвестный тип
      уведомления.

      Если ваше приложение получило тип нотификации которое еще не
      поддерживается, то его нужно залогировать или пропустить, но **обязательно
      ответить HTTP кодом 200**.


      #### type:message

      Нотификация с типом message будет содержать value c полями:

      ```

      "value": {
        "id": "256347f56e4819deb6f8c59ff14d62a8",
        "type": "text",
        "chat_id": "u2i-1123-1123",
        "user_id": 94235311,
        "author_id": 78743309,
        "created": 1566290351,
        "content": {
          "text": "привет"
        }
      ```

      * id – идентификатор сообщения. Уникален только в рамках чата, в котором
      находится сообщение

      * chat_id – идентификатор чата

      * user_id – идентификатор пользователя, для которого пришло сообщение

      * author_id – идентификатор пользователя, создавшего сообщение

      * created – время создания сообщения, unix timestamp

      * type – тип сообщения. Типы сообщений поддерживаются: text, image, item,
      location, call, link

      * content – тело сообщения. Поля такие же как и в [API получения
      сообщений](https://api.avito.ru/docs/api.html#operation/getMessages)


      **Важно отметить**, что в мессенджере Авито есть системные сообщения в
      чатах. В данный момент они выглядят в API как текстовые сообщения с
      текстом `Сообщение не поддерживается. Пожалуйста, перейдите в Авито
      мессенджер <ССЫЛКА>`. В будущем мы планируем добавить полноценную
      поддержку платформенных сообщений в наше API.


      ### Уведомления V1 (DEPRECATED, используйте v2)

      HTTP запрос к вашей системе будет содержать следующий payload:

      ```

      {
          "id": "c7a799b4-c6f3-4d8c-88cc-6d7a1d69e6f8",
          "version": "v1.0.0",
          "timestamp": 1566290351,
          "messages": [
            {
              "id": "256347f56e4819deb6f8c59ff14d62a8",
              "chat_id": "u2i-1773856013-78743309",
              "user_id": 94235311,
              "author_id": 78743309,
              "created": 1566290351,
              "type": "text",
              "content": {
                "text": "asd"
              }
            }
          ]
        }
      ```

      Если тип сообщения не поддерживается в нотификациях, поле content будет
      пустым объектом.


      Уведомление содержит поля:

      * id – идентификатор уведомления. С его помощью вы можете определить
      доставлялось ли в вашему сайту такое уведомление или нет для избежания
      дублирования сообщений.

      * version – версия уведомлений. Версия отражает текущую структуру
      уведомлений: название и типы полей. Если изменится структура, то и
      изменится версия согласно Semantic Versioning Specification

      * timestamp – время создания уведомления, unix timestamp

      * messages – массив объектов сообщений


      Объекты массива **messages** содержат поля:

      * id – идентификатор сообщения. Уникален только в рамках чата, в котором
      находится сообщение

      * chat_id – идентификатор чата

      * user_id – идентификатор пользователя, для которого пришло сообщение

      * author_id – идентификатор пользователя, создавшего сообщение

      * created – время создания сообщения, unix timestamp

      * type – тип сообщения. Типы сообщений поддерживаются такие же как и в API
      получения сообщений

      * content – тело сообщения. Поля такие же как и в [API получения
      сообщений](https://api.avito.ru/docs/api.html#operation/getMessages)
  - name: Cpa
    x-displayName: CPA
    description: |
      Методы для работы с сервисом CPA
  - name: Marketplace
    x-displayName: Marketplace Partner API
    description: >
      Программный интерфейс доступа к заказам продавца,

      предназначенный для управления своими заказами через собственную
      логистическую систему учета заказов.
  - name: MarketplaceSandbox
    x-displayName: Marketplace Sandbox Partner API
    description: >
      Программный интерфейс доступа к заказам продавца,

      предназначенный для управления своими заказами через собственную
      логистическую систему учета заказов.


      Внимание! Это выделенный контур для выполнения запросов в тестовое
      окружение.

      Все запросы, выполняемые здесь изолированны от боевого контура Marketplace
      Partner API.
paths:
  /token/:
    get:
      tags:
        - Access
      operationId: getAccessToken
      summary: Получение access token
      description: Получения временного ключа для авторизации
  /token/?grant_type=authorization_code:
    get:
      tags:
        - ApplicationAccess
      operationId: getAccessTokenAuthorizationCode
      summary: Получение access token
      description: Получения временного ключа для авторизации запроса от лица пользователя
  /token/?grant_type=refresh_token:
    get:
      tags:
        - ApplicationAccess
      operationId: refreshAccessTokenAuthorizationCode
      summary: Обновление access token
      description: Обновление временного ключа для авторизации запроса от лица пользователя
  '/autoload/v1/accounts/{user_id}/reports/':
    get:
      tags:
        - Autoload
      operationId: getReports
      summary: Список отчетов об автозагрузке
      description: |
        Отчеты отсортированы в порядке убывания даты загрузки,
        т.е. самый свежий отчет будет в самом начале списка
      security:
        - Authorization Code:
            - 'autoload:reports'
        - Client Credentials: []
  '/autoload/v1/accounts/{user_id}/reports/{reportId}/':
    get:
      tags:
        - Autoload
      operationId: getReportById
      summary: Получение данных отчета по ID
      description: |
        Возвращает данные одного отчета об автозагрузке по ID отчета
      security:
        - Authorization Code:
            - 'autoload:reports'
        - Client Credentials: []
  '/autoload/v1/accounts/{user_id}/reports/last_report/':
    get:
      tags:
        - Autoload
      operationId: getLastReport
      summary: Получение данных последнего актуального отчета
      description: |
        Возвращает данные отчета о последнем завершенном цикле автозагрузки
      security:
        - Authorization Code:
            - 'autoload:reports'
        - Client Credentials: []
  '/autoload/v1/accounts/{user_id}/items/{ad_id}/':
    get:
      tags:
        - Autoload
      operationId: getAutoloadItemInfo
      summary: Получение информации о выгрузке объявления
      description: |
        Возвращает данные отчета о выгрузке объявления на сайт **avito.ru**
      security:
        - Authorization Code:
            - 'autoload:reports'
        - Client Credentials: []
  /core/v1/items:
    get:
      tags:
        - Item
      operationId: getItemsInfo
      summary: Получение информации по объявлениям
      description: >
        Возвращает список объявлений авторизованного пользователя - статус,
        категорию и ссылку на сайте
      security:
        - Authorization Code:
            - 'items:info'
        - Client Credentials: []
  '/core/v1/accounts/{user_id}/items/{item_id}/':
    get:
      tags:
        - Item
      operationId: getItemInfo
      summary: Получение информации по объявлению
      description: >
        Возвращает данные об объявлении - его статус, список примененных услуг,
        статистику просмотров


        **Внимание:** для получения статистики рекомендуется использование
        методов

        [Получение статистики по одному объявлению](#operation/itemStatsDeep)
        или

        [Получение статистики по списку объявлений](#operation/itemStatsShallow)
      security:
        - Authorization Code:
            - 'items:info'
        - Client Credentials: []
  '/core/v1/accounts/{user_id}/stats/items':
    post:
      tags:
        - Item
      deprecated: true
      operationId: getItemsStats
      summary: Получение статистики по объявлениям
      description: >
        Получение статистики по списку идентификаторов объявлений на сайте.


        **Внимание:** это deprecated method, который будет выключен 1 декабря
        2020 года.


        **Внимание:** для получения статистики рекомендуется использование
        методов

        [Получение статистики по одному объявлению](#operation/itemStatsDeep)
        или

        [Получение статистики по списку объявлений](#operation/itemStatsShallow)
      security:
        - Authorization Code:
            - 'items:info'
        - Client Credentials: []
  '/core/v1/accounts/{user_id}/calls/stats/':
    post:
      tags:
        - Item
      operationId: postCallsStats
      summary: Получение статистики по звонкам
      description: |
        Получение агрегированной статистики звонков, полученных пользователем
      security:
        - Authorization Code:
            - 'items:info'
        - Client Credentials: []
  '/core/v1/accounts/{user_id}/price/vas':
    post:
      tags:
        - Item
      operationId: getVasPrices
      summary: Получение информации о стоимости дополнительных услуг
      description: >
        Возвращает в ответ объект со следующей структурой:

        - `vas` – объект, который содержит информацию о стоимости дополнительных
        услуг для каждого объявления.

        Ключами являются идентификаторы объявлений, значениями – объекты с
        информацией о стоимости услуг для данного объявления:
          - `highlight` — [услуга продвижения "Выделить"](https://support.avito.ru/articles/200026858)
          - `xl` – [услуга продвижения "XL-объявление"](https://support.avito.ru/articles/685)
        - `errors` – идентификаторы объявлений, для которых информация не
        получена.
      security:
        - Authorization Code:
            - 'items:info'
        - Client Credentials: []
  '/core/v1/accounts/{user_id}/price/vas_packages':
    post:
      tags:
        - Item
      operationId: getVasPackagePrice
      summary: Получение информации о стоимости пакетов дополнительных услуг
      description: >
        Возвращает в ответ объект со следующей структурой:

        - `packages` – объект, который содержит информацию о стоимости пакетов
        дополнительных услуг для каждого объявления.

        Ключами являются идентификаторы объявлений, значениями – объекты с
        информацией о стоимости пакетов услуг для данного объявления:
          - `x2_1` - [пакет "до 2 раз больше просмотров на 1 день"](https://support.avito.ru/articles/1398)
          - `x2_7` - [пакет "до 2 раз больше просмотров на 7 дней"](https://support.avito.ru/articles/1398)
          - `x5_1` - [пакет "до 5 раз больше просмотров на 1 день"](https://support.avito.ru/articles/1398)
          - `x5_7` - [пакет "до 5 раз больше просмотров на 7 дней"](https://support.avito.ru/articles/1398)
          - `x10_1` - [пакет "до 10 раз больше просмотров на 1 день"](https://support.avito.ru/articles/1398)
          - `x10_7` - [пакет "до 10 раз больше просмотров на 7 дней"](https://support.avito.ru/articles/1398)
        - `errors` – идентификаторы объявлений, для которых информация не
        получена.
      security:
        - Authorization Code:
            - 'items:info'
        - Client Credentials: []
  '/core/v1/accounts/{user_id}/items/{item_id}/vas':
    put:
      tags:
        - Item
      operationId: putItemVas
      summary: Применение дополнительных услуг
      description: >
        Применение дополнительной услуги к объявлению, в ответе возвращает
        данные о примененной услуге и сумму списания.

        [Более подробная информация по дополнительным
        услугам](https://support.avito.ru/sections/200009758)
      security:
        - Authorization Code:
            - 'items:apply_vas'
        - Client Credentials: []
  '/core/v2/accounts/{user_id}/items/{item_id}/vas_packages':
    put:
      tags:
        - Item
      operationId: putItemVasPackageV2
      summary: Применение пакета дополнительных услуг
      description: >
        Применение пакета дополнительных услуг к объявлению, в ответе возвращает
        сумму списания
      security:
        - Authorization Code:
            - 'items:apply_vas'
        - Client Credentials: []
  '/core/v1/accounts/{user_id}/items/{item_id}/bookings':
    post:
      tags:
        - Realty
      operationId: putBookingsInfo
      summary: Заполнение календаря занятости объекта недвижимости
      description: >
        Заполнение календаря занятости объекта недвижимости (для краткосрочной
        аренды)
      security:
        - Authorization Code:
            - 'short_term_rent:write'
        - Client Credentials: []
  /core/v1/accounts/self:
    get:
      tags:
        - User
      operationId: getUserInfoSelf
      summary: Получение информации об авторизованном пользователе
      description: |
        Возвращает идентификатор пользователя и его регистрационные данные
      security:
        - Authorization Code:
            - 'user:read'
        - Client Credentials: []
  '/core/v1/accounts/{user_id}/balance/':
    get:
      tags:
        - User
      operationId: getUserBalance
      summary: Получение баланса кошелька пользователя
      description: >
        Возвращает сумму реальных денежных средств в кошельке, а также сумму
        бонусных средств
      security:
        - Authorization Code:
            - 'user_balance:read'
        - Client Credentials: []
  /core/v1/accounts/operations_history/:
    post:
      tags:
        - User
      operationId: postOperationsHistory
      summary: Получение истории операций пользователя
      description: >
        Возвращает список операций пользователя (списания/пополнение кошелька -
        деньги и бонусы) за определенный временной период (задается
        пользователем)
      security:
        - Authorization Code:
            - 'user_operations:read'
        - Client Credentials: []
  /autoteka/v1/request-preview-by-item-id:
    post:
      tags:
        - Autoteka
      operationId: postPreviewByItemId
      summary: Запрос на создание превью по ID объявления
      description: >
        Возвращает идентификатор `previewId`, по которому асинхронно с помощью
        [запроса на получение превью по ID](#operation/getPreview) можно
        получить результат
      security:
        - Authorization Code:
            - 'autoteka:previews'
        - Client Credentials: []
  /autoteka/v1/request-preview-by-regnumber:
    post:
      tags:
        - Autoteka
      operationId: postPreviewByRegNumber
      summary: Запрос на создание превью по государственному номеру
      description: >
        Возвращает идентификатор `previewId`, по которому асинхронно с помощью
        [запроса на получение превью по ID](#operation/getPreview) можно
        получить результат
      security:
        - Authorization Code:
            - 'autoteka:previews'
        - Client Credentials: []
  /autoteka/v1/previews:
    post:
      tags:
        - Autoteka
      operationId: postPreviewByVin
      summary: Запрос на создание превью по VIN
      description: >
        Возвращает идентификатор `previewId`, по которому асинхронно с помощью
        [запроса на получение превью по ID](#operation/getPreview) можно
        получить результат
      security:
        - Authorization Code:
            - 'autoteka:previews'
        - Client Credentials: []
  '/autoteka/v1/previews/{previewId}':
    get:
      tags:
        - Autoteka
      operationId: getPreview
      summary: |
        Запрос на получение превью по ID
      description: >
        Возвращает текущий статус сбора информации превью, и краткую инфо по
        запрашиваемому `VIN`
      security:
        - Authorization Code:
            - 'autoteka:previews'
        - Client Credentials: []
  /autoteka/v1/reports:
    post:
      tags:
        - Autoteka
      operationId: postReport
      summary: |
        Запрос на создание отчета по превью
      description: >
        Метод для запроса отчета по `previewId`, возвращает идентификатор отчета
        по которому сформированный отчет можно получить в [методе для получения
        отчета по его идентификатору](#operation/getReport). При запросе
        происходит списание доступных отчетов
      security:
        - Authorization Code:
            - 'autoteka:reports'
        - Client Credentials: []
  '/autoteka/v1/reports/{report_id}':
    get:
      tags:
        - Autoteka
      operationId: getReport
      summary: |
        Метод для получения отчета по ID
      description: >
        Получение подробного отчета по его идентификатору, полученному из
        [запроса на создание отчета](#operation/postReport)
      security:
        - Authorization Code:
            - 'autoteka:reports'
        - Client Credentials: []
  /autoteka/v1/reports/list/:
    get:
      tags:
        - Autoteka
      operationId: getReportList
      summary: |
        Метод для получения списка отчётов
      description: >
        Получение списка запрошенных ранее отчетов [запроса на создание
        отчета](#operation/postReport)
      security:
        - Authorization Code:
            - 'autoteka:reports'
        - Client Credentials: []
    put:
      tags:
        - Autoteka
      operationId: putReport
      summary: >
        Метод для обновление отчета по его идентификатору в случае отсуствия
        данных
      description: >
        Запрос на перегенерацию отчета по ID, который был получен из [запроса на
        создание отчета](#operation/postReport)
      security:
        - Authorization Code:
            - 'autoteka:reports'
        - Client Credentials: []
  /autoteka/v1/packages/active_package:
    get:
      tags:
        - Autoteka
      operationId: getActivePackage
      summary: |
        Метод для запроса остатка отчётов в текущем пакете пользователя
      description: |
        Возвращает остаток отчётов в текущем пакете пользователя
      security:
        - Authorization Code:
            - 'autoteka:reports'
        - Client Credentials: []
  /marketplace/shipment/getInfo:
    post:
      tags:
        - Marketplace
      summary: Информация об отправлении
      description: |
        Возвращает информацию об отправлении по его идентификатору.
      security:
        - Client Credentials: []
      operationId: ShipmentGetInfo
  /marketplace/shipment/getList:
    post:
      tags:
        - Marketplace
      summary: Список отправлений
      description: |
        Возвращает список отправлений за указанный период времени.

        Дополнительно можно отфильтровать отправления.

        Максимальное количество отправлений в ответе: 50
      security:
        - Client Credentials: []
      operationId: ShipmentGetList
  /marketplace/shipment/confirm:
    post:
      tags:
        - Marketplace
      summary: Подтвердить отправление
      description: |
        Выполнить подтверждение отправления продавцом.
      security:
        - Client Credentials: []
      operationId: ShipmentConfirm
  /marketplace/shipment/reject:
    post:
      tags:
        - Marketplace
      summary: Отменить отправление
      description: |
        Выполнить отмену отправления продавцом.
      security:
        - Client Credentials: []
      operationId: ShipmentReject
  /marketplace/shipment/assemble:
    post:
      tags:
        - Marketplace
      summary: Скомплектовать товар(-ы) для отправления
      description: |
        Выполнить комплектацию товара(-ов) для отправления продавцом
      security:
        - Client Credentials: []
      operationId: ShipmentAssemble
  /marketplace/shipment/pickup:
    post:
      tags:
        - Marketplace
      summary: Подтвердить отгрузку товара(-ов) на отправление
      description: |
        Подтвердить отгрузку товара(-ов) на отправление
      security:
        - Client Credentials: []
      operationId: ShipmentPickUp
  /marketplace/shipment/createAcceptanceCert:
    post:
      tags:
        - Marketplace
      summary: Получить PDF-файл акта приёма-передачи
      description: |
        Получить PDF-файл акта приёма-передачи
      security:
        - Client Credentials: []
      operationId: ShipmentCreateAcceptanceCert
  /marketplace-sandbox/shipment/getInfo:
    post:
      tags:
        - MarketplaceSandbox
      summary: Информация об отправлении
      description: |
        Возвращает информацию об отправлении по его идентификатору.
      security:
        - Client Credentials: []
      operationId: ShipmentGetInfoSandbox
  /marketplace-sandbox/shipment/getList:
    post:
      tags:
        - MarketplaceSandbox
      summary: Список отправлений
      description: |
        Возвращает список отправлений за указанный период времени.

        Дополнительно можно отфильтровать отправления.

        Максимальное количество отправлений в ответе: 50
      security:
        - Client Credentials: []
      operationId: ShipmentGetListSandbox
  /marketplace-sandbox/shipment/confirm:
    post:
      tags:
        - MarketplaceSandbox
      summary: Подтвердить отправление
      description: |
        Выполнить подтверждение отправления продавцом.
      security:
        - Client Credentials: []
      operationId: ShipmentConfirmSandbox
  /marketplace-sandbox/shipment/reject:
    post:
      tags:
        - MarketplaceSandbox
      summary: Отменить отправление
      description: |
        Выполнить отмену отправления продавцом.
      security:
        - Client Credentials: []
      operationId: ShipmentRejectSandbox
  /marketplace-sandbox/shipment/assemble:
    post:
      tags:
        - MarketplaceSandbox
      summary: Скомплектовать товар(-ы) для отправления
      description: |
        Выполнить комплектацию товара(-ов) для отправления продавцом
      security:
        - Client Credentials: []
      operationId: ShipmentAssembleSandbox
  /marketplace-sandbox/shipment/pickup:
    post:
      tags:
        - MarketplaceSandbox
      summary: Подтвердить отгрузку товара(-ов) на отправление
      description: |
        Подтвердить отгрузку товара(-ов) на отправление
      security:
        - Client Credentials: []
      operationId: ShipmentPickUpSandbox
  /marketplace-sandbox/shipment/createAcceptanceCert:
    post:
      tags:
        - MarketplaceSandbox
      summary: Получить PDF-файл акта приёма-передачи
      description: |
        Получить PDF-файл акта приёма-передачи
      security:
        - Client Credentials: []
      operationId: ShipmentCreateAcceptanceCert
  '/realty/v1/accounts/{user_id}/items/{item_id}/prices':
    post:
      tags:
        - Realty
      operationId: postRealtyPrices
      summary: |
        Актуализация параметров для выбранных периодов
      description: >
        Обновляет параметры (цена за ночь, доплата за гостя, минимальная
        продолжительность брони) для

        каждого из переданных диапазонов дат
      security:
        - Authorization Code:
            - 'short_term_rent:write'
        - Client Credentials: []
  '/realty/v1/accounts/{user_id}/items/{item_id}/bookings':
    get:
      tags:
        - Realty
      operationId: getRealtyBookings
      summary: |
        Получение списка броней по объявлению
      description: |
        Возвращает информацию о бронированиях объекта за весь период.
      security:
        - Authorization Code:
            - 'short_term_rent:read'
        - Client Credentials: []
  /job/v1/vacancies:
    post:
      tags:
        - Job
      operationId: postVacancy
      summary: Публикация вакансии
      description: |
        Создает объявление в категории Вакансии
      security:
        - Authorization Code:
            - 'job:write'
        - Client Credentials: []
  '/job/v1/vacancies/{vacancy_id}':
    put:
      tags:
        - Job
      operationId: putVacancy
      summary: Редактирование вакансии
      description: |
        Редактирует объявление в категории Вакансии
      security:
        - Authorization Code:
            - 'job:write'
        - Client Credentials: []
  '/job/v1/vacancies/archived/{vacancy_id}':
    put:
      tags:
        - Job
      operationId: putArchivedVacancy
      summary: Остановка публикации вакансии
      description: |
        Снимает с публикации объявление в категории Вакансии
      security:
        - Authorization Code:
            - 'job:write'
        - Client Credentials: []
  '/job/v1/vacancies/{vacancy_id}/prolongate':
    post:
      tags:
        - Job
      operationId: postProlongateVacancy
      summary: Реактивация вакансии
      description: |
        Реактивирует объявление в категории Вакансии
      security:
        - Authorization Code:
            - 'job:write'
        - Client Credentials: []
  /job/v1/resumes/:
    get:
      tags:
        - Job
      operationId: getResumes
      summary: |
        Поиск резюме
      security:
        - Authorization Code:
            - 'job:cv'
        - Client Credentials: []
  '/job/v1/resumes/{resume_id}/':
    get:
      deprecated: true
      tags:
        - Job
      operationId: getResume
      summary: |
        Просмотр резюме
      security:
        - Authorization Code:
            - 'job:cv'
        - Client Credentials: []
  '/job/v2/resumes/{resume_id}/':
    get:
      tags:
        - Job
      operationId: getResume 2.0
      summary: |
        Просмотр резюме v2.0
      description: >
        По умолчанию fields и params выводятся все. Если указана только часть
        полей - остальные поля будут отсутствовать в ответе.
      security:
        - Authorization Code:
            - 'job:cv'
        - Client Credentials: []
  '/job/v1/resumes/{resume_id}/contacts/':
    get:
      tags:
        - Job
      operationId: getResumeContacts
      summary: |
        Доступ к контактным данным соискателя
      description: >
        Для получения контактов пользователя необходимо приобрести пакет
        просмотров

        контактных данных в [личном
        кабинете](https://www.avito.ru/account/cv_packages).
      security:
        - Authorization Code:
            - 'job:cv'
        - Client Credentials: []
  /job/v1/negotiations:
    get:
      tags:
        - Job
      operationId: getNegotiations
      summary: |
        Получение списка откликов
      description: |
        Возвращает постраничный список откликов с фильтрацией по вакансии
      security:
        - Authorization Code:
            - 'job:negotiations'
        - Client Credentials: []
  '/job/v1/negotiations/{negotiation_id}':
    get:
      tags:
        - Job
      operationId: getNegotiationsByID
      summary: |
        Получение отклика по его идентификатору
      description: |
        Возвращает информацию об отклике
      security:
        - Authorization Code:
            - 'job:negotiations'
        - Client Credentials: []
  '/job/v1/negotiations/by-chat-id/{chat_id}':
    get:
      tags:
        - Job
      operationId: getNegotiationsByChatID
      summary: |
        Получение отклика по идентификатору чата
      description: >
        Возвращает информацию об отклике. Отклики создаются после создания чата
        и поэтому в ответе метода появляются не сразу (до 30 секунд)
      security:
        - Authorization Code:
            - 'job:negotiations'
        - Client Credentials: []
  /messenger/v1/webhook:
    post:
      tags:
        - Messenger
      operationId: postWebhook
      summary: Включение уведомлений (webhooks)
      description: |
        Включение уведомлений
      security:
        - Authorization Code:
            - 'messenger:read'
        - Client Credentials: []
  /messenger/v2/webhook:
    post:
      tags:
        - Messenger
      operationId: postWebhookV2
      summary: Включение уведомлений V2 (webhooks)
      description: |
        Включение **V2** уведомлений. <LINK_TO_V2_WEBHOOKS>
      security:
        - Authorization Code:
            - 'messenger:read'
        - Client Credentials: []
  /messenger/v1/webhook/unsubscribe:
    post:
      tags:
        - Messenger
      operationId: postWebhookUnsubscribe
      summary: Отключение уведомлений (webhooks)
      description: |
        Отключение уведомлений
      security:
        - Authorization Code:
            - 'messenger:read'
        - Client Credentials: []
  '/messenger/v1/accounts/{user_id}/blacklist':
    post:
      tags:
        - Messenger
      operationId: postBlacklist
      summary: Добавление пользователя в blacklist
      description: |
        Добавление пользователя в blacklist
      security:
        - Authorization Code:
            - 'messenger:write'
        - Client Credentials: []
  '/messenger/v1/accounts/{user_id}/chats/{chat_id}/messages/':
    get:
      tags:
        - Messenger
      operationId: getMessages
      summary: Получение списка сообщений
      description: >
        Получение списка сообщений, используйте только для изначальной загрузки
        сообщений на экране, для получения новых сообщений в реальном времени
        используйте webhooks
      security:
        - Authorization Code:
            - 'messenger:read'
        - Client Credentials: []
  '/messenger/v2/accounts/{user_id}/chats/{chat_id}/messages/':
    get:
      tags:
        - Messenger
      operationId: getMessagesV2
      summary: Получение списка сообщений V2
      description: >
        Получение списка сообщений.  **Не помечает чат прочитанным**

        После успешного списка сообщений необходимо вызвать
        [метод](https://api.avito.ru/docs/api.html#operation/chatRead), который
        сделат чат прочитанным.
      security:
        - Authorization Code:
            - 'messenger:read'
        - Client Credentials: []
  '/messenger/v1/accounts/{user_id}/chats/{chat_id}/messages':
    post:
      tags:
        - Messenger
      operationId: postSendMessage
      summary: Отправление сообщения
      description: |
        На данный момент можно отправить только текстовое сообщение
      security:
        - Authorization Code:
            - 'messenger:write'
        - Client Credentials: []
  '/messenger/v1/accounts/{user_id}/chats/{chat_id}':
    get:
      tags:
        - Messenger
      operationId: getChatById
      summary: Получение информации по чату
      description: |
        Возвращает данные чата и последнее сообщение в нем
      security:
        - Authorization Code:
            - 'messenger:read'
        - Client Credentials: []
  '/messenger/v1/accounts/{user_id}/chats':
    get:
      tags:
        - Messenger
      operationId: getChats
      summary: Получение информации по чатам
      description: |
        Возвращает список чатов
      security:
        - Authorization Code:
            - 'messenger:read'
        - Client Credentials: []
  '/messenger/v1/accounts/{user_id}/chats/{chat_id}/read':
    post:
      tags:
        - Messenger
      operationId: chatRead
      summary: Прочитать чат
      description: >
        После успешного получения списка сообщений необходимо вызвать этот метод
        для того, чтобы чат стал прочитанным.
      security:
        - Authorization Code:
            - 'messenger:read'
        - Client Credentials: []
  '/messenger/v1/accounts/{user_id}/chats/{chat_id}/messages/{message_id}':
    post:
      tags:
        - Messenger
      operationId: deleteMessage
      summary: Удаление сообщения
      description: >
        Сообщение не пропадает из истории, а меняет свой тип на deleted.

        Удалять можно только те сообщения которые не старше часа с момента их
        создания.
      security:
        - Authorization Code:
            - 'messenger:write'
        - Client Credentials: []
  '/cpa/v1/call/{call_id}':
    get:
      tags:
        - Cpa
      operationId: getCall
      summary: Запись звонка
      description: Получение записи звонка по идентификатору
      security:
        - Client Credentials: []
  '/stats/v1/accounts/{user_id}/items':
    post:
      tags:
        - Item
      operationId: itemStatsShallow
      summary: Получение статистики по списку объявлений
      description: >
        Получение счетчиков по переданному списку объявлений пользователя.


        **Внимание:** в запросе может быть передано не более 200 идентификаторов
        объявлений.


        **Внимание:** глубина такого запроса ограничена 270 днями.


        ### Счетчики

        * views - общее число просмотров объявления;

        * uniqViews - число уникальных пользователей, просмотревших объявление;

        * contacts - число [контактов] [1];

        * uniqContacts - число уникальных пользователей, совершивших [контакты]
        [1];

        * favorites - число добавлений объявления в "избранное";

        * uniqFavorites - число уникальных пользователей, добавивших объявление
        в "избранное".


        ### Группировка счетчиков

        Счетчики могут быть сгруппированы [2] по:

        * дням;

        * неделям - в поле `date` соответствующей структуры будет первый день
        недели;

        * месяцам - в поле `date` соответствующей структуры будет первый день
        месяца.


        #### Период группировки

        Период группировки передается в теле запроса в поле `group_by`.
        Доступные значения этого поля:

        * "day" (по умолчанию) - без группировки;

        * "week" - суммирование счетчиков за неделю;

        * "month" - суммирование счетчиков за месяц.


        ### Примечания

        * [1]: Под контактом понимаются: запросы телефона продавца, начатый чат
        с продавцом по конкретному объявлению, отклик на резюме и пр.

        * [2]: Группировка уникальных пользователей происходит только в рамках
        одного дня.
      security:
        - Authorization Code:
            - 'stats:read'
        - Client Credentials: []
  '/stats/v1/accounts/{user_id}/items/{item_id}/':
    post:
      tags:
        - Item
      deprecated: true
      operationId: itemStatsDeep
      summary: Получение статистики по одному объявлению
      description: >
        Получение счетчиков по одному объявлению пользователя.


        **Внимание:** глубина такого запроса ограничена 540 днями.


        **Внимание:** это deprecated method, который будет выключен 1 января
        2021 года.


        ### Счетчики

        * views - общее число просмотров объявления;

        * uniqViews - число уникальных пользователей, просмотревших объявление;

        * contacts - число [контактов] [1];

        * uniqContacts - число уникальных пользователей, совершивших [контакты]
        [1];

        * favorites - число добавлений объявления в "избранное";

        * uniqFavorites - число уникальных пользователей, добавивших объявление
        в "избранное".


        ### Группировка счетчиков

        Счетчики могут быть сгруппированы [2] по:

        * дням;

        * неделям - в поле `date` соответствующей структуры будет первый день
        недели;

        * месяцам - в поле `date` соответствующей структуры будет первый день
        месяца.


        #### Период группировки

        Период группировки передается в теле запроса в поле `group_by`.
        Доступные значения этого поля:

        * "day" (по умолчанию) - без группировки;

        * "week" - суммирование счетчиков за неделю;

        * "month" - суммирование счетчиков за месяц.


        ### Примечания

        * [1]: Под контактом понимаются: запросы телефона продавца, начатый чат
        с продавцом по конкретному объявлению, отклик на резюме и пр.

        * [2]: Группировка уникальных пользователей происходит только в рамках
        одного дня.
      security:
        - Authorization Code:
            - 'stats:read'
        - Client Credentials: []
components:
  securitySchemes:
    Client Credentials:
      type: oauth2
      description: >-
        Это API использует OAuth 2 с механизмом client_credentials. Используйте
        его для доступа к возможностям своей личной учетной записи.
        [Подробнее](#tag/Access)
      flows:
        clientCredentials:
          tokenUrl: 'https://api.avito.ru/token'
          scopes: {}
    Authorization Code:
      type: oauth2
      description: >-
        Это API использует OAuth 2 с механизмом authorization_code. Используйте
        его для доступа к данным других пользователей при разработке стороннего
        приложения. [Подробнее](#tag/ApplicationAccess)
      flows:
        authorizationCode:
          authorizationUrl: 'https://avito.ru/oauth'
          tokenUrl: 'https://api.avito.ru/token'
          scopes:
            'messenger:read': Чтение сообщений в мессенджере Авито
            'messenger:write': Модифицирование сообщений в мессенджере Авито
            'user_balance:read': Получение баланса пользователя
            'job:write': Изменение объявлений вертикали Работа
            'job:cv': Получение информации резюме
            'job:negotiations': Получение информации об откликах на вакансии
            'user_operations:read': Получение истории операций пользователя
            'user:read': Получение информации о пользователе
            'autoload:reports': Получение отчетов Автозагрузки
            'items:info': Получение информации об объявлениях
            'items:apply_vas': Применение дополнительных услуг
            'short_term_rent:read': Получение информации об объявлениях краткосрочной аренды
            'short_term_rent:write': Изменение объявлений краткосрочной аренды
            'autoteka:reports': Получение и создание отчетов Автотеки
            'autoteka:previews': Получение и создание превью Автотеки
            'autoteka:vin': Получение vin по идентификатору объявления
            'stats:read': Получение статистики объявлений