<?php
/**
 * ChatPublicUserProfileAvatarImagesTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Авито API для бизнеса
 *
 * # Общая информация Описание API произведено в формате [**Swagger 3.0**](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md). Вы можете использовать данный файл для ознакомления с методами API, а также для генерации базового кода для работы с API на удобном для вас языке программирования с помощью утилиты [**Swagger Codegen**](https://swagger.io/swagger-codegen/) или online сервиса [**Swagger Editor**](https://editor.swagger.io/).  **Авито API для бизнеса предоставляется согласно [Условиям использования](https://api.avito.ru/docs/public/APITermsOfServiceV1.pdf).**  По всем вопросам работы с API необходимо обращаться в Службу Поддержки профессиональных инструментов:  <li>телефон: <b>+7 495 777-10-66</b></li> <li>email: <a href=\"mailto:supportautoload@avito.ru\">supportautoload@avito.ru</a></li>  # Типы авторизации Для использования данного API запрос должен быть авторизован. В данный момент API Авито использует следующие механизмы авторизации.  <!-- ReDoc-Inject: <security-definitions> -->  Подробнее о каждом механизме и его назначении можно прочитать в соответствующем разделе.
 *
 * OpenAPI spec version: 1
 * Contact: supportautoload@avito.ru
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.23
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * ChatPublicUserProfileAvatarImagesTest Class Doc Comment
 *
 * @category    Class
 * @description ChatPublicUserProfileAvatarImages
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ChatPublicUserProfileAvatarImagesTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ChatPublicUserProfileAvatarImages"
     */
    public function testChatPublicUserProfileAvatarImages()
    {
    }

    /**
     * Test attribute "_128x128"
     */
    public function testProperty128x128()
    {
    }

    /**
     * Test attribute "_192x192"
     */
    public function testProperty192x192()
    {
    }

    /**
     * Test attribute "_24x24"
     */
    public function testProperty24x24()
    {
    }

    /**
     * Test attribute "_256x256"
     */
    public function testProperty256x256()
    {
    }

    /**
     * Test attribute "_36x36"
     */
    public function testProperty36x36()
    {
    }

    /**
     * Test attribute "_48x48"
     */
    public function testProperty48x48()
    {
    }

    /**
     * Test attribute "_64x64"
     */
    public function testProperty64x64()
    {
    }

    /**
     * Test attribute "_72x72"
     */
    public function testProperty72x72()
    {
    }

    /**
     * Test attribute "_96x96"
     */
    public function testProperty96x96()
    {
    }
}
