<?php
/**
 * JobApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Авито API для бизнеса
 *
 * # Общая информация Описание API произведено в формате [**Swagger 3.0**](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md). Вы можете использовать данный файл для ознакомления с методами API, а также для генерации базового кода для работы с API на удобном для вас языке программирования с помощью утилиты [**Swagger Codegen**](https://swagger.io/swagger-codegen/) или online сервиса [**Swagger Editor**](https://editor.swagger.io/).  **Авито API для бизнеса предоставляется согласно [Условиям использования](https://api.avito.ru/docs/public/APITermsOfServiceV1.pdf).**  По всем вопросам работы с API необходимо обращаться в Службу Поддержки профессиональных инструментов:  <li>телефон: <b>+7 495 777-10-66</b></li> <li>email: <a href=\"mailto:supportautoload@avito.ru\">supportautoload@avito.ru</a></li>  # Типы авторизации Для использования данного API запрос должен быть авторизован. В данный момент API Авито использует следующие механизмы авторизации.  <!-- ReDoc-Inject: <security-definitions> -->  Подробнее о каждом механизме и его назначении можно прочитать в соответствующем разделе.
 *
 * OpenAPI spec version: 1
 * Contact: supportautoload@avito.ru
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.23
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use Swagger\Client\Configuration;
use Swagger\Client\ApiException;
use Swagger\Client\ObjectSerializer;

/**
 * JobApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class JobApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for getNegotiations
     *
     * Получение списка откликов.
     *
     */
    public function testGetNegotiations()
    {
    }

    /**
     * Test case for getNegotiationsByChatID
     *
     * Получение отклика по идентификатору чата.
     *
     */
    public function testGetNegotiationsByChatID()
    {
    }

    /**
     * Test case for getNegotiationsByID
     *
     * Получение отклика по его идентификатору.
     *
     */
    public function testGetNegotiationsByID()
    {
    }

    /**
     * Test case for getResume
     *
     * Просмотр резюме.
     *
     */
    public function testGetResume()
    {
    }

    /**
     * Test case for getResume20
     *
     * Просмотр резюме v2.0.
     *
     */
    public function testGetResume20()
    {
    }

    /**
     * Test case for getResumeContacts
     *
     * Доступ к контактным данным соискателя.
     *
     */
    public function testGetResumeContacts()
    {
    }

    /**
     * Test case for getResumes
     *
     * Поиск резюме.
     *
     */
    public function testGetResumes()
    {
    }

    /**
     * Test case for postProlongateVacancy
     *
     * Реактивация вакансии.
     *
     */
    public function testPostProlongateVacancy()
    {
    }

    /**
     * Test case for postVacancy
     *
     * Публикация вакансии.
     *
     */
    public function testPostVacancy()
    {
    }

    /**
     * Test case for putArchivedVacancy
     *
     * Остановка публикации вакансии.
     *
     */
    public function testPutArchivedVacancy()
    {
    }

    /**
     * Test case for putVacancy
     *
     * Редактирование вакансии.
     *
     */
    public function testPutVacancy()
    {
    }
}
