<?php
/**
 * MarketplaceSandboxApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Авито API для бизнеса
 *
 * # Общая информация Описание API произведено в формате [**Swagger 3.0**](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md). Вы можете использовать данный файл для ознакомления с методами API, а также для генерации базового кода для работы с API на удобном для вас языке программирования с помощью утилиты [**Swagger Codegen**](https://swagger.io/swagger-codegen/) или online сервиса [**Swagger Editor**](https://editor.swagger.io/).  **Авито API для бизнеса предоставляется согласно [Условиям использования](https://api.avito.ru/docs/public/APITermsOfServiceV1.pdf).**  По всем вопросам работы с API необходимо обращаться в Службу Поддержки профессиональных инструментов:  <li>телефон: <b>+7 495 777-10-66</b></li> <li>email: <a href=\"mailto:supportautoload@avito.ru\">supportautoload@avito.ru</a></li>  # Типы авторизации Для использования данного API запрос должен быть авторизован. В данный момент API Авито использует следующие механизмы авторизации.  <!-- ReDoc-Inject: <security-definitions> -->  Подробнее о каждом механизме и его назначении можно прочитать в соответствующем разделе.
 *
 * OpenAPI spec version: 1
 * Contact: supportautoload@avito.ru
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.23
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use Swagger\Client\Configuration;
use Swagger\Client\ApiException;
use Swagger\Client\ObjectSerializer;

/**
 * MarketplaceSandboxApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class MarketplaceSandboxApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for shipmentAssembleSandbox
     *
     * Скомплектовать товар(-ы) для отправления.
     *
     */
    public function testShipmentAssembleSandbox()
    {
    }

    /**
     * Test case for shipmentConfirmSandbox
     *
     * Подтвердить отправление.
     *
     */
    public function testShipmentConfirmSandbox()
    {
    }

    /**
     * Test case for shipmentCreateAcceptanceCert
     *
     * Получить PDF-файл акта приёма-передачи.
     *
     */
    public function testShipmentCreateAcceptanceCert()
    {
    }

    /**
     * Test case for shipmentGetInfoSandbox
     *
     * Информация об отправлении.
     *
     */
    public function testShipmentGetInfoSandbox()
    {
    }

    /**
     * Test case for shipmentGetListSandbox
     *
     * Список отправлений.
     *
     */
    public function testShipmentGetListSandbox()
    {
    }

    /**
     * Test case for shipmentPickUpSandbox
     *
     * Подтвердить отгрузку товара(-ов) на отправление.
     *
     */
    public function testShipmentPickUpSandbox()
    {
    }

    /**
     * Test case for shipmentRejectSandbox
     *
     * Отменить отправление.
     *
     */
    public function testShipmentRejectSandbox()
    {
    }
}
