<?php
/**
 * MessengerApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Авито API для бизнеса
 *
 * # Общая информация Описание API произведено в формате [**Swagger 3.0**](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md). Вы можете использовать данный файл для ознакомления с методами API, а также для генерации базового кода для работы с API на удобном для вас языке программирования с помощью утилиты [**Swagger Codegen**](https://swagger.io/swagger-codegen/) или online сервиса [**Swagger Editor**](https://editor.swagger.io/).  **Авито API для бизнеса предоставляется согласно [Условиям использования](https://api.avito.ru/docs/public/APITermsOfServiceV1.pdf).**  По всем вопросам работы с API необходимо обращаться в Службу Поддержки профессиональных инструментов:  <li>телефон: <b>+7 495 777-10-66</b></li> <li>email: <a href=\"mailto:supportautoload@avito.ru\">supportautoload@avito.ru</a></li>  # Типы авторизации Для использования данного API запрос должен быть авторизован. В данный момент API Авито использует следующие механизмы авторизации.  <!-- ReDoc-Inject: <security-definitions> -->  Подробнее о каждом механизме и его назначении можно прочитать в соответствующем разделе.
 *
 * OpenAPI spec version: 1
 * Contact: supportautoload@avito.ru
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.23
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use Swagger\Client\Configuration;
use Swagger\Client\ApiException;
use Swagger\Client\ObjectSerializer;

/**
 * MessengerApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class MessengerApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for chatRead
     *
     * Прочитать чат.
     *
     */
    public function testChatRead()
    {
    }

    /**
     * Test case for deleteMessage
     *
     * Удаление сообщения.
     *
     */
    public function testDeleteMessage()
    {
    }

    /**
     * Test case for getChatById
     *
     * Получение информации по чату.
     *
     */
    public function testGetChatById()
    {
    }

    /**
     * Test case for getChats
     *
     * Получение информации по чатам.
     *
     */
    public function testGetChats()
    {
    }

    /**
     * Test case for getMessages
     *
     * Получение списка сообщений.
     *
     */
    public function testGetMessages()
    {
    }

    /**
     * Test case for getMessagesV2
     *
     * Получение списка сообщений V2.
     *
     */
    public function testGetMessagesV2()
    {
    }

    /**
     * Test case for postBlacklist
     *
     * Добавление пользователя в blacklist.
     *
     */
    public function testPostBlacklist()
    {
    }

    /**
     * Test case for postSendMessage
     *
     * Отправление сообщения.
     *
     */
    public function testPostSendMessage()
    {
    }

    /**
     * Test case for postWebhook
     *
     * Включение уведомлений (webhooks).
     *
     */
    public function testPostWebhook()
    {
    }

    /**
     * Test case for postWebhookUnsubscribe
     *
     * Отключение уведомлений (webhooks).
     *
     */
    public function testPostWebhookUnsubscribe()
    {
    }

    /**
     * Test case for postWebhookV2
     *
     * Включение уведомлений V2 (webhooks).
     *
     */
    public function testPostWebhookV2()
    {
    }
}
